### ISSUE TITLE
Could or be possible for me to put this to Mac os

### ISSUE THREAD

**Issue by gotjoshua** [rolandbernard/marvin#66]
As it's an electron app, is there any reason it could never run on Mac os?

**Comment by rolandbernard** [comment]
Yes, it is possible to port this project to macOS. I do not own a device running macOS, so I will not do it myself, but you are welcome to port it, and I am open to merging your changes.

The basic functionality should already work regardless of the platform, but there is some platform-specific code (e.g., for finding and launching the available application, the location of specific files, executing commands, etc.).

The first step in porting this project should be to get it to build. For that, I see the following things that must be done:
* Add `"darwin"` to the `"os"` list
* Add a `mac` entry in the `electron-builder.yml` file to configure the build. (Documentation for this can be found [here](https://www.electron.build))
    Something like this, I guess (not sure if the icon has to be a specific format):
    ```
    mac:
        icon: ./static/logo.png
            category: public.app-category.utilities
            target:
                - dmg
                - zip
            publish:
                - github
    ```

After that, all the functionality that does not depend on the system (e.g., calculator, web search, translation, etc.) should already work, but to get the rest to work, you have to make some more changes:
* You will have to define a new value for the `Platform` enum in `src/common/platform.ts`
* After that, TypeScript should already give you errors at all the places that have to be changed
* Nearly all the platform-specific code is inside the `src/main/adapters/` directory, so I would start there

This is all I can think of so far, but I am sure that once you start to port the project you, will find some more things that need to be adapted.
